// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "architecture/backend.mdx": () => import("../content/docs/architecture/backend.mdx?collection=docs"), "architecture/data-models.mdx": () => import("../content/docs/architecture/data-models.mdx?collection=docs"), "architecture/frontend.mdx": () => import("../content/docs/architecture/frontend.mdx?collection=docs"), "architecture/index.mdx": () => import("../content/docs/architecture/index.mdx?collection=docs"), "api-reference/admin.mdx": () => import("../content/docs/api-reference/admin.mdx?collection=docs"), "api-reference/auth.mdx": () => import("../content/docs/api-reference/auth.mdx?collection=docs"), "api-reference/chat.mdx": () => import("../content/docs/api-reference/chat.mdx?collection=docs"), "api-reference/incremental-updates.mdx": () => import("../content/docs/api-reference/incremental-updates.mdx?collection=docs"), "api-reference/repositories.mdx": () => import("../content/docs/api-reference/repositories.mdx?collection=docs"), "configuration/environment-variables.mdx": () => import("../content/docs/configuration/environment-variables.mdx?collection=docs"), "deployment/ai-providers.mdx": () => import("../content/docs/deployment/ai-providers.mdx?collection=docs"), "deployment/database.mdx": () => import("../content/docs/deployment/database.mdx?collection=docs"), "deployment/docker-compose.mdx": () => import("../content/docs/deployment/docker-compose.mdx?collection=docs"), "getting-started/docker-deployment.mdx": () => import("../content/docs/getting-started/docker-deployment.mdx?collection=docs"), "getting-started/index.mdx": () => import("../content/docs/getting-started/index.mdx?collection=docs"), "getting-started/local-development.mdx": () => import("../content/docs/getting-started/local-development.mdx?collection=docs"), "getting-started/windows-deployment.mdx": () => import("../content/docs/getting-started/windows-deployment.mdx?collection=docs"), "mcp/index.mdx": () => import("../content/docs/mcp/index.mdx?collection=docs"), }),
};
export default browserCollections;